# Shizuku Aurora — Gradle 全局属性
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# 版本元信息（与官方 Shizuku 的 versionCode=commitCount 语义对齐）
aurora.versionCode=1000
aurora.versionName=14.0.0-aurora
